### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [thiago-porto25/Postr#1]
Failed to compile.

Error in ./src/App.js
Syntax error: C:/Users/Horacio/Postr/src/App.js: Unexpected token (12:25)

  10 | import { SuspenseFallback } from './components/molecules'
  11 | 
> 12 | const Start = lazy(() => import('./pages/start'))
     |                          ^
  13 | const Login = lazy(() => import('./pages/login'))
  14 | const SignUp = lazy(() => import('./pages/signup'))
  15 | const ResetPassword = lazy(() => import('./pages/reset-password'))

**Comment by thiago-porto25** [comment]
Hello, could you provide more context to this error?

**Comment by HoracioLopezCarvajal** [comment]
Just downloaded installed using npm start I get the error I need it to train a group of programmers for various projects in react and react native

**Comment by HoracioLopezCarvajal** [comment]
./src/hooks/useAuthListener.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\hooks'

**Comment by thiago-porto25** [comment]
You must create your own config.js file in the firebase directory. It should look like this.

```
import { initializeApp } from 'firebase/app'
import {
  getFirestore,
  collection,
  getDoc,
  getDocs,
  setDoc,
  addDoc,
  updateDoc,
  arrayUnion,
  arrayRemove,
  serverTimestamp,
  doc,
  onSnapshot,
  query,
  where,
  deleteDoc,
  orderBy,
  limit,
  writeBatch,
  startAt,
  endAt,
  increment,
  collectionGroup,
} from 'firebase/firestore'
import {
  deleteUser,
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut,
  onAuthStateChanged,
  sendEmailVerification,
  sendPasswordResetEmail,
} from 'firebase/auth'

const firebaseConfig = {/* Your firebase project credentials here */}

// Initialize Firebase

const app = initializeApp(firebaseConfig)

const db = getFirestore(app)
const auth = getAuth(app)

export {
  db,
  collection,
  collectionGroup,
  getDoc,
  getDocs,
  setDoc,
  addDoc,
  updateDoc,
  arrayUnion,
  arrayRemove,
  serverTimestamp,
  doc,
  onSnapshot,
  query,
  where,
  deleteDoc,
  orderBy,
  limit,
  writeBatch,
  startAt,
  endAt,
  increment,
  auth,
  signInWithEmailAndPassword,
  signOut,
  createUserWithEmailAndPassword,
  onAuthStateChanged,
  sendEmailVerification,
  sendPasswordResetEmail,
  deleteUser,
}
```

**Comment by HoracioLopezCarvajal** [comment]
Thank you very much, it works perfectly for anything here we are greetings

**Comment by thiago-porto25** [comment]
You're welcome!

**Comment by HoracioLopezCarvajal** [comment]
Good, sorry again I have done what you told me and it keeps coming out Failed to compile

./src/hooks/useAuthListener.js
Module not found: Can't resolve '../firebase/config' in 'C: \ Users \ Horacio \ Postr \ src \ hooks'

It works and sometimes this comes out
Failed to compile
./src/hooks/useAuthListener.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\hooks'

**Comment by HoracioLopezCarvajal** [comment]
Uncaught Error: Cannot find module '../firebase/config'
    at webpackMissingModule (index.js:7)
    at Module.<anonymous> (index.js:7)
    at Module../src/hooks/useAuthListener.js (useAuthListener.js:11)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Module.<anonymous> (index.js:3)
    at Module../src/hooks/index.js (index.js:7)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Module.<anonymous> (main.chunk.js:17)
    at Module../src/App.js (App.js:103)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Module.<anonymous> (useProfilePosts.js:5)
    at Module../src/index.js (index.js:10)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Object.1 (parseTimestamp.js:4)
    at __webpack_require__ (bootstrap:856)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

**Comment by HoracioLopezCarvajal** [comment]
./src/helpers/ProtectedRoute.js
Attempted import error: 'Redirect' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/helpers/IsUserRedirect.js
Attempted import error: 'Redirect' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/components/templates/SettingsTemplate.js
Attempted import error: 'Switch' is not exported from 'react-router'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/App.js
Attempted import error: 'Switch' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
2index.js:1 ./src/components/organisms/SearchBar.js
Attempted import error: 'useHistory' is not exported from 'react-router'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
2index.js:1 ./src/components/molecules/PostCard.js
Attempted import error: 'useHistory' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
2index.js:1 ./src/components/molecules/BigPostCard.js
Attempted import error: 'useHistory' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
2index.js:1 ./src/components/organisms/SettingsOrg.js
Attempted import error: 'useHistory' is not exported from 'react-router-dom'.
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/hooks/useAuthListener.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\hooks'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/services/commentServices.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\services'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/services/postServices.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\services'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/services/followServices.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\services'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/services/authServices.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\services'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 ./src/services/firebase.js
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\services'
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
localhost/:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by thiago-porto25** [comment]
'Attempted import error: 'Redirect' is not exported from 'react-router-dom'.' Try importing Redirect from react-router-dom in the file for Protected Route

**Comment by HoracioLopezCarvajal** [comment]
Muchas gracias
