### ISSUE TITLE
ERROR REPEAT I TAKE 3 HOURS TRYING TO SOLVE

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [thiago-porto25/Postr#2]
Good,
Module not found: Can't resolve '../firebase/config' in 'C:\Users\Horacio\Postr\src\hooks'

**Comment by thiago-porto25** [comment]
I am sorry for the late response, did you check if the path '../firebase/config' is correct?. Is the config file exporting everything correctly?

**Comment by thiago-porto25** [comment]
Closed due to inactivity
